services:
  - type: web
    name: ai-900-prep
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
